### ISSUE TITLE
Shortcuts in Quick Add

### ISSUE THREAD

**Issue by amazansky** [MyHomeworkSpace/client#129]
- We should have a shortcut (think ctrl+enter or cmd+enter) to skip the regular add modal that would pop up after pressing enter in quick add. We should think about how we want to handle any required fields that aren't entered at the time this shortcut is activated though. (For example, the class could be automatically assigned to "Other" if a class isn't entered - see #128)
- The escape key should unfocus/take the user out of Quick Add. Optionally, pressing ctrl+space again could also do the same thing.

**Comment by thatoddmailbox** [comment]
So I added support for direct submission by holding down literally any modifier key (Alt, Control, Shift, and _maybe_ Command? Need someone on macOS to verify that) and pressing Enter. I don't really know where the best place to document this is. I suppose we could put it in the keyboard shortcuts modal, but then we might want to add a specific "Quick Add" section. We could also maybe just add it somewhere in the Quick Add popup? "Enter to submit / Shift+Enter to really submit"?

Also right now, if there's an error, it will open up the homework modal with as much information you gave it and whatever error there was. I think we could maybe make this a bit more elegant (like maybe it could just blink the "unknown due date" or "unknown class" text red a few times when you try to submit it, instead of opening a whole new modal?) but it works for now. #128 is also something that could be considered for the class assignment, but we probably still want to require due dates for new homework.

**Comment by willbarkoff** [comment]
@thatoddmailbox <kbd>command</kbd> + <kbd>enter</kbd> doesn't work on macOS; however <kbd>control</kbd> + <kbd>enter</kbd> does.

In terms of suggesting the keyboard shortcuts, maybe something like this would work, but I think it would have to be a bit more subtle.
<img width="483" alt="image" src="https://user-images.githubusercontent.com/10969136/80840710-dc5e2200-8bcb-11ea-99b4-75eae6b4df0c.png">

**Comment by thatoddmailbox** [comment]
Huh, that's weird. Was that in Firefox? I'm pretty sure e.metaKey should work for Command...can you try a different browser?

Also, for the text underneath: it feels a bit weird to say press enter to modify. Shouldn't they just modify by editing the text that's there? Not sure on that one though.

**Comment by willbarkoff** [comment]
That was in Firefox 76.0b8, and I also tested it in Safari 13.1 (both on macOS 10.15.4), and <kbd>command</kbd> + <kbd>enter</kbd> doesn't work on either of them

**Comment by thatoddmailbox** [comment]
Should be fixed now.
