### ISSUE TITLE
DaltonTab Image of the Day

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#13]
Add bing image of the day for Wallpaper. Can use DaltonTab code.

**Comment by nywillb** [comment]
Changing this to DaltonTab image of the day, because DaltonTab no longer uses bing images

**Comment by nywillb** [comment]
Ok, so DaltonTab currently uses a _super secret_ website, daltontabservices.myhomework.space, which serves without a valid [`Access-Control-Allow-Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header. This hasn't mattered in the past, as the new tab page and WebExtensions have special rules.

The easy way to do this is to add myhomework.space to the `Access-Control-Allow-Origin` header, and implement it with daltontabservices.myhomework.space, but the better way to do this, is probably to migrate DaltonTab Services to MyHomeworkSpace/api-server](github.com/myhomeworkspace/api-server), so everything can be in one place, and we could pick the issues 

The issue with migrating DaltonTab Services is that you would need to make sure that everyone's extension updated to a verison with the new API server url, otherwise people's extensions might stop working. Luckally, both Chrome and Firefox are very good about automatically updating extensions; however, we could make sure that the updates are complete by montitoring pings to daltontabservices.myhomework.space, as we currently do.

The other issue is authentication. We have DaltonTab users who don't use MyHomeworkSpace, so it would be nice if they didn't have to sign into MyHomeworkSpace to get the background images; however, DaltonTab currently uses the new API with Bearer tokens, which requires a sign in. DaltonTab could switch back to the old csrf system just for the one API call; however, that doesn't seem like the best option.

Another option is to use [Unsplash Source](https://source.unsplash.com/) rather than the DaltonTab image, as it already exists and is nice. One more option might be just to ditch DaltonTab Services altogether, handle color selection on the client side, and maintain an Unsplash Collection of all the images, and use the Unsplash API.

**Comment by nywillb** [comment]
Didn't mean to close

**Comment by thatoddmailbox** [comment]
I don't think there's a great reason to migrate the DaltonTab services code to MyHomeworkSpace, as we wouldn't really gain anything. It handles a lot more than just images, so the Unsplash Source idea wouldn't work so well (and, plus, it's nice to be able to override the image with something not from Unsplash) I also don't really understand what you're talking about with authentication -- the DaltonTab APIs don't have any concept of authentication, as there's nothing in there that shouldn't be public.

**Comment by nywillb** [comment]
I'm perfectly fine with leaving DaltonTab services how it is. What I was trying to say about the authentication is that currently, to use MyHomeworkSpace APIs, DaltonTab needs to request permission from the user using the MyHomeworkSpace application auth flow, so if we did move DaltonTab services to MyHomeworkSpace, it would be nice to not require users to sign into the application auth flow to get the background image.
