### ISSUE TITLE
Combined Homework/Calendar view

### ISSUE THREAD

**Issue by amazansky** [MyHomeworkSpace/client#131]
In the spirit of keeping "all your homework in one place", I think we should have some sort of combined view which integrates both homework entries and calendar events. This could just be as simple as adding calendar events to the current Homework view, just with a time attached and maybe some styling to differentiate the fact that it's a calendar event, but it could also possibly be an entirely different view which combines both homework and cal events in some clever way.

Also, as part of this new view, we should make a Quick Add feature for calendar events, and combine that with the existing Quick Add for Homework.

**Comment by thatoddmailbox** [comment]
I'm taking off the low priority label from this because it actually seems somewhat important to me...the weird split between homework and calendar items is something that's bothered me for a while, especially when you have events like "meet with someone" that you'd want to see on your homework view _and_ on your calendar. (you can technically do that with the homework events, but that's an incredibly clunky interface)

I'm not totally sure what the solution is, but it seems like there should be a greater connection between the two views. Right now it feels like the calendar is somewhat bolted onto the side of everything else.

**Comment by thatoddmailbox** [comment]
Semi-related: #53, #100

**Comment by thatoddmailbox** [comment]
Random thought: if we're putting calendar events on Homework view, it's not really much of a Homework view anymore, is it? Would we want to rename the tab to something like "Overview"? Or does that bring up too many memories of "Today is Tuesday, April 28, 2020"...

**Comment by amazansky** [comment]
Ah. Yes, I was thinking that we should probably have a separate name but I couldn't come up with anything. Overview seems acceptable but we should try to think of some other stuff too.

**Comment by thatoddmailbox** [comment]
What about "My Day"? :smile:

**Comment by willbarkoff** [comment]
See #137 for a discussion regarding a potential new name for homework view
