### ISSUE TITLE
Add support for outside schools

### ISSUE THREAD

**Issue by willbarkoff** [MyHomeworkSpace/client#78]
This would be possible considering that blackbaud's rate-limiting is username based, so if you get 5 incorrect passwords, you are only not allowed to sign in with _that username_, sign-in requests will still be accepted from that IP. Proof:
![proof](https://user-images.githubusercontent.com/10969136/35065417-3485b1fa-fb9b-11e7-8928-53202ea6019d.gif)
(Yes, I know I didn't need proof, but I gave it anyway to make things easier to understand. Also I know that the colors are all screwed up and it's slow. Too bad. It demonstrates the concept anyway)

The only places where we actually use a dalton.org domain is [here](https://github.com/MyHomeworkSpace/api-server/blob/8dc1c1ab87600ccf382ec59da22e0015e0440e00/auth/login.go#L18), [here](https://github.com/MyHomeworkSpace/api-server/blob/8dc1c1ab87600ccf382ec59da22e0015e0440e00/auth/login.go#L23), and [here](https://github.com/MyHomeworkSpace/api-server/blob/8dc1c1ab87600ccf382ec59da22e0015e0440e00/auth/login.go#L24). (Yes I know that I didn't need to link three lines in one file and I could have just linked the file but I had already done it when I realized that. What we would need to do is just redo the sign in (both client and server) to ask for either email and password, or school website, username, and password (more likely, because sampleschool.edu/app redirects to that school's myschoolapp, for example <https://dalton.org/app> redirects to <https://dalton.myschoolapp.com>, and <https://www.trinityschoolnyc.org/app> redirects to <https://trinityschoolnyc.myschoolapp.com>). This would allow MyHomeworkSpace to work with any school that uses [Blackbaud OnCampus](http://k12.blackbaud.com/products/oncampus-learning-management-system/). PLEASE POINT OUT ANY FLAWS IN THIS THAT YOU SEE BECUASE THERE ARE PROBABLY MANY!

**Comment by Tpixelminer** [comment]
If your going to expand to other schools, you should make a proper terms and conditions and make sure it's displayed properly. I can see some admins not liking the idea of having an external planner app that uses their website. If you put the liability on the student for signing up, then you can't be blamed/get in trouble for for using that sign in method.

**Comment by nywillb** [comment]
@Tpixelminer: <http://legal.myhomework.space/privacy/> exits. It probably would need to be updated though.

**Comment by nywillb** [comment]
So after doing some research, I found that the /app link doesn't always work.

Example:
<https://www.westminster.net> - Links to school website
<https://www.westminster.net/app> - 404s
<https://www.westminster.net> - Links to school website
<https://westminster.myschoolapp.com> - Links to MySchoolApp

**Comment by thatoddmailbox** [comment]
The code has been refactored in a way that this could be supported; however, the problem is that this definitely would require individual setup for each school. Different schools have weird scheduling requirements (like Dalton with its rotating fridays) or even simpler things like multiple terms.

Blackbaud knows about all of these complexities on the administration side of things (it has to), but I don't think it's possible to get access to that information as a regular student. It might be possible to make queries on behalf of the student (so we'd treat Blackbaud as a blackbox that just gives us scheduling data for a given week/month/whatever) but that would require some way of keeping the student's session alive over a long period of time, which I'm not sure is possible...

**Comment by willbarkoff** [comment]
This was done awhile ago.
